[2024-05-12T15:45:10.016+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T15:45:10.057+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_mlops_dag.load manual__2024-05-12T15:44:23.742376+00:00 [queued]>
[2024-05-12T15:45:10.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_mlops_dag.load manual__2024-05-12T15:44:23.742376+00:00 [queued]>
[2024-05-12T15:45:10.075+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-12T15:45:10.124+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-05-12 15:44:23.742376+00:00
[2024-05-12T15:45:10.137+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'simple_mlops_dag', 'load', 'manual__2024-05-12T15:44:23.742376+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp6qddbwv7']
[2024-05-12T15:45:10.141+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask load
[2024-05-12T15:45:10.147+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-12T15:45:10.148+0000] {standard_task_runner.py:63} INFO - Started process 87 to run task
[2024-05-12T15:45:10.251+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_mlops_dag.load manual__2024-05-12T15:44:23.742376+00:00 [running]> on host 885b0ae9b1ba
[2024-05-12T15:45:10.741+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='simple_mlops_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T15:44:23.742376+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T15:44:23.742376+00:00'
[2024-05-12T15:45:10.753+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T15:45:11.053+0000] {logging_mixin.py:188} INFO - -----------Storing data------------
[2024-05-12T15:45:11.069+0000] {logging_mixin.py:188} INFO - Error storing data: [Errno 13] Permission denied: 'dvc'
[2024-05-12T15:45:11.069+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-12T15:45:11.071+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T15:45:11.087+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_mlops_dag, task_id=load, run_id=manual__2024-05-12T15:44:23.742376+00:00, execution_date=20240512T154423, start_date=20240512T154510, end_date=20240512T154511
[2024-05-12T15:45:11.130+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-12T15:45:11.155+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T15:45:11.156+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
